CREATE DATABASE MUSIC

GO

USE MUSIC

GO 

CREATE TABLE Artist

(ArtistId SMALLINT NOT NULL PRIMARY KEY IDENTITY,

ArtistName NVARCHAR(200) NOT NULL,

Description NVARCHAR(200) NOT NULL,

Text nText NOT NULL );

CREATE TABLE Album
(AlbumId SMALLINT NOT NULL PRIMARY KEY IDENTITY(100,1),

AlbumTitle NVARCHAR(200) NOT NULL,

AlbumCover NVARCHAR(200) NOT NULL);

CREATE TABLE Song
(SongId SMALLINT NOT NULL PRIMARY KEY IDENTITY,

SongName NVARCHAR(200) NOT NULL,

SongLink NVARCHAR(200) NULL );